# apiVersion: v1
# kind: Service
# metadata:
#   name: springboot-service
# spec:
#   selector:
#     app: springboot-demo
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8081
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: springboot-active
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
