# ====== use default rollout =====
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: springboot-demo
#   labels:
#     app: springboot-demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: springboot-demo
#   template:
#     metadata:
#       labels:
#         app: springboot-demo
#     spec:
#       containers:
#       - name: springboot
#         image: iyuyisenga/springboot-demo:v2.2.7
#         ports:
#         - containerPort: 8081


# ====== rollout using blue-green ==========
# rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: springboot-demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot
          image: iyuyisenga/springboot-demo:v2.2.9
          ports:
            - containerPort: 8081
  strategy:
    blueGreen:
      activeService: springboot-active        # Live production traffic
      previewService: springboot-preview      # Preview new version
      autoPromotionEnabled: false             # Requires manual promotion (safer for testing)
      scaleDownDelaySeconds: 30               # Delay before scaling down old pods after promotion
