name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # temurin is recommended now

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Run tests
      - name: Run tests with Maven
        run: mvn test

      # Analyze with SonarCloud
    #   - name: SonarCloud Scan
    #     uses: SonarSource/sonarcloud-github-action@v2
    #     with:
    #       projectBaseDir: .
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
    #       SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}


      
          # Upload .jar artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar
