# name: Release Docker Image and Update Samplechart values with new tag

# on:
#   push:
#     tags:
#       - 'v*.*.*'

# permissions:
#   contents: write  # Required to push changes back to the repo

# jobs:
#   docker:
#     runs-on: ubuntu-24.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           java-version: '17'
#           distribution: 'temurin'

#       - name: Build project
#         run: mvn clean package -DskipTests

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Registry
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}

#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}

#       - name: Update deployment.yaml with the new image tag
#         run: |
#           TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
#           IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
#           echo "Updating image to $IMAGE_NAME:$TAG"
#           sed -i "s|^\(\s*image:\s*\).*$|\1${IMAGE_NAME}:${TAG}|" k8s/deployment.yaml
#           cat k8s/deployment.yaml

#       - name: Commit and push updated deployment.yaml
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add k8s/deployment.yaml
#           git commit -m "Update image tag to ${GITHUB_REF_NAME}"
#           git push origin HEAD:main

#       - name: Clone samplecharts repo with token
#         run: |
#           git clone https://x-access-token:${{ secrets.SAMPLECHARTS_PAT }}@github.com/benitha200/samplecharts.git

#       - name: Update values.yaml with new tag
#         run: |
#           TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
#           VALUES_FILE="samplecharts/charts/springboot-chart/values.yaml"
#           echo "Updating tag in $VALUES_FILE to $TAG"
#           sed -i "s|^\(\s*tag:\s*\).*$|\1${TAG}|" "$VALUES_FILE"
#           cat "$VALUES_FILE"

#       - name: Commit and push updated values.yaml to samplecharts repo
#         working-directory: samplecharts
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add charts/springboot-chart/values.yaml
#           git commit -m "Update springboot-chart image tag to ${GITHUB_REF_NAME}"
#           git push origin main

name: CI/CD Workflow for Docker Image and Chart Version Management

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'charts/cherryapp-chart/values.yaml'

permissions:
  contents: write  # Required to push changes back to the repo

jobs:
  bump-chart-version:
    if: contains(github.event.head_commit.message, 'Update springboot-chart image tag') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump Chart Version
        run: |
          CHART_FILE=charts/cherryapp-chart/Chart.yaml
          VERSION=$(grep '^version:' $CHART_FILE | awk '{print $2}')
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF += 1; print}')
          echo "Bumping version: $VERSION -> $NEW_VERSION"
          sed -i "s/^version: .*/version: $NEW_VERSION/" $CHART_FILE

      - name: Commit and push updated Chart.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/cherryapp-chart/Chart.yaml
          git commit -m "chore: bump chart version to $NEW_VERSION [skip ci]"
          git push

  docker:
    runs-on: ubuntu-24.04
    needs: [bump-chart-version]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Update deployment.yaml with the new image tag
        run: |
          TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
          IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
          echo "Updating image to $IMAGE_NAME:$TAG"
          sed -i "s|^\(\s*image:\s*\).*$|\1${IMAGE_NAME}:${TAG}|" k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${GITHUB_REF_NAME}"
          git push origin HEAD:main

      - name: Clone samplecharts repo with token
        run: |
          git clone https://x-access-token:${{ secrets.SAMPLECHARTS_PAT }}@github.com/benitha200/samplecharts.git

      - name: Update values.yaml with new tag
        run: |
          TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
          VALUES_FILE="samplecharts/charts/springboot-chart/values.yaml"
          echo "Updating tag in $VALUES_FILE to $TAG"
          sed -i "s|^\(\s*tag:\s*\).*$|\1${TAG}|" "$VALUES_FILE"
          cat "$VALUES_FILE"

      - name: Commit and push updated values.yaml to samplecharts repo
        working-directory: samplecharts
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add charts/springboot-chart/values.yaml
          git commit -m "Update springboot-chart image tag to ${GITHUB_REF_NAME}"
          git push origin main

